### Importing Libraries

In [415]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix, accuracy_score

### Loading Dataset

In [416]:
dataset = pd.read_csv('.//datasets//MusicGenreClassification.csv')
target_column = 'Class'
dataset

Artist Name                             Track Name  \
0                 Bruno Mars  That's What I Like (feat. Gucci Mane)   
1                     Boston                           Hitch a Ride   
2              The Raincoats                     No Side to Fall In   
3                       Deno             Lingo (feat. J.I & Chunkz)   
4      Red Hot Chili Peppers      Nobody Weird Like Me - Remastered   
...                      ...                                    ...   
17991            Green-House                              Find Home   
17992               Micatone                               All Gone   
17993        Smash Hit Combo                           Peine perdue   
17994                Beherit                         Salomon's Gate   
17995         The Raconteurs                     Broken Boy Soldier   

       Popularity  danceability  energy   key  loudness  mode  speechiness  \
0            60.0         0.854   0.564   1.0    -4.964     1       0.0485   
1            54.0         0.382   0.814   3.0    -7.230     1       0.0406   
2            35.0         0.434   0.614   6.0    -8.334     1       0.0525   
3            66.0         0.853   0.597  10.0    -6.528     0       0.0555   
4            53.0         0.167   0.975   2.0    -4.279     1       0.2160   
...           ...           ...     ...   ...       ...   ...          ...   
17991        35.0         0.166   0.109   7.0   -17.100     0       0.0413   
17992        27.0         0.638   0.223  11.0   -10.174     0       0.0329   
17993        34.0         0.558   0.981   4.0    -4.683     0       0.0712   
17994        29.0         0.215   0.805   6.0   -12.757     0       0.1340   
17995        43.0         0.400   0.853   4.0    -5.320     0       0.0591   

       acousticness  instrumentalness  liveness  valence    tempo  \
0          0.017100               NaN    0.0849   0.8990  134.071   
1          0.001100          0.004010    0.1010   0.5690  116.454   
2          0.486000          0.000196    0.3940   0.7870  147.681   
3          0.021200               NaN    0.1220   0.5690  107.033   
4          0.000169          0.016100    0.1720   0.0918  199.060   
...             ...               ...       ...      ...      ...   
17991      0.993000          0.824000    0.0984   0.1770  171.587   
17992      0.858000          0.000016    0.0705   0.3350   73.016   
17993      0.000030          0.000136    0.6660   0.2620  105.000   
17994      0.001290          0.916000    0.2560   0.3550  131.363   
17995      0.006040          0.212000    0.3340   0.3770  138.102   

       duration_in min/ms  time_signature  Class  
0                234596.0               4      5  
1                251733.0               4     10  
2                109667.0               4      6  
3                173968.0               4      5  
4                229960.0               4     10  
...                   ...             ...    ...  
17991            193450.0               3      6  
17992            257067.0               4      2  
17993            216222.0               4      8  
17994            219693.0               4      8  
17995            182227.0               4     10  

[17996 rows x 17 columns]

In [417]:
if "Unnamed: 0" in dataset.columns:
    dataset.drop("Unnamed: 0",axis=1,inplace=True)
dataset

Artist Name                             Track Name  \
0                 Bruno Mars  That's What I Like (feat. Gucci Mane)   
1                     Boston                           Hitch a Ride   
2              The Raincoats                     No Side to Fall In   
3                       Deno             Lingo (feat. J.I & Chunkz)   
4      Red Hot Chili Peppers      Nobody Weird Like Me - Remastered   
...                      ...                                    ...   
17991            Green-House                              Find Home   
17992               Micatone                               All Gone   
17993        Smash Hit Combo                           Peine perdue   
17994                Beherit                         Salomon's Gate   
17995         The Raconteurs                     Broken Boy Soldier   

       Popularity  danceability  energy   key  loudness  mode  speechiness  \
0            60.0         0.854   0.564   1.0    -4.964     1       0.0485   
1            54.0         0.382   0.814   3.0    -7.230     1       0.0406   
2            35.0         0.434   0.614   6.0    -8.334     1       0.0525   
3            66.0         0.853   0.597  10.0    -6.528     0       0.0555   
4            53.0         0.167   0.975   2.0    -4.279     1       0.2160   
...           ...           ...     ...   ...       ...   ...          ...   
17991        35.0         0.166   0.109   7.0   -17.100     0       0.0413   
17992        27.0         0.638   0.223  11.0   -10.174     0       0.0329   
17993        34.0         0.558   0.981   4.0    -4.683     0       0.0712   
17994        29.0         0.215   0.805   6.0   -12.757     0       0.1340   
17995        43.0         0.400   0.853   4.0    -5.320     0       0.0591   

       acousticness  instrumentalness  liveness  valence    tempo  \
0          0.017100               NaN    0.0849   0.8990  134.071   
1          0.001100          0.004010    0.1010   0.5690  116.454   
2          0.486000          0.000196    0.3940   0.7870  147.681   
3          0.021200               NaN    0.1220   0.5690  107.033   
4          0.000169          0.016100    0.1720   0.0918  199.060   
...             ...               ...       ...      ...      ...   
17991      0.993000          0.824000    0.0984   0.1770  171.587   
17992      0.858000          0.000016    0.0705   0.3350   73.016   
17993      0.000030          0.000136    0.6660   0.2620  105.000   
17994      0.001290          0.916000    0.2560   0.3550  131.363   
17995      0.006040          0.212000    0.3340   0.3770  138.102   

       duration_in min/ms  time_signature  Class  
0                234596.0               4      5  
1                251733.0               4     10  
2                109667.0               4      6  
3                173968.0               4      5  
4                229960.0               4     10  
...                   ...             ...    ...  
17991            193450.0               3      6  
17992            257067.0               4      2  
17993            216222.0               4      8  
17994            219693.0               4      8  
17995            182227.0               4     10  

[17996 rows x 17 columns]

## Preprocessing

### Remove Date Columns

In [418]:
if "date" in dataset.columns:
    dataset.drop("date",inplace=True,axis=1)
    print("date Deleted")
if "Date" in dataset.columns:
    dataset.drop("Date",inplace=True,axis=1)
    print("Date Deleted")
if "id" in dataset.columns:
    dataset.drop("id",inplace=True,axis=1)
    print("id Deleted")
if "ID" in dataset.columns:
    dataset.drop("ID",inplace=True,axis=1)
    print("ID Deleted")

### Remove Dollar signs

In [419]:
dollar = '$'
prices_list = []
if(len(dataset) > 100):
    for column in dataset.columns:
        X = dataset[column][:50].values
        for val in X:
            if( "$" in str(val)):
                prices_list.append(column)
                break;
            break;
            
prices_list

[]

In [420]:
new_2darray = []
if(prices_list):
    cost_values = dataset[prices_list].values
    for array in cost_values:
        new_array = []
        for val in array:
            new_val = (re.sub("[^0-9]", "", val))
            if new_val:
                new_val = float(new_val)
            else:
                new_val = np.NaN
            new_array.append(new_val)
        new_2darray.append(new_array)
new_2darray

[]

In [421]:
if(prices_list):
    prices_data = pd.DataFrame(new_2darray,columns= prices_list)

In [422]:
if(prices_list):
    dataset.drop(prices_list,inplace=True,axis=1)

In [423]:
if(prices_list):
    dataset[prices_list] = prices_data

### Define Index / ID Columns and Target Columns

In [424]:

id1 = "id"

### Categorize into numerical and categorical

In [425]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Artist Name         17996 non-null  object 
 1   Track Name          17996 non-null  object 
 2   Popularity          17568 non-null  float64
 3   danceability        17996 non-null  float64
 4   energy              17996 non-null  float64
 5   key                 15982 non-null  float64
 6   loudness            17996 non-null  float64
 7   mode                17996 non-null  int64  
 8   speechiness         17996 non-null  float64
 9   acousticness        17996 non-null  float64
 10  instrumentalness    13619 non-null  float64
 11  liveness            17996 non-null  float64
 12  valence             17996 non-null  float64
 13  tempo               17996 non-null  float64
 14  duration_in min/ms  17996 non-null  float64
 15  time_signature      17996 non-null  int64  
 16  Clas

In [426]:
cat_cols = []
num_cols = []

columns = dataset.columns
if id1 in dataset.columns:
    dataset.drop(id1,inplace=True,axis=1)

datatypes = dataset.dtypes
datatypes

for i in range(len(datatypes)):
    if datatypes.index[i] != target_column:
        if datatypes[i]=='object':
            unqval = dataset[datatypes.index[i]].nunique()
            if (unqval < 30):
                cat_cols.append(datatypes.index[i])
            else:
                del dataset[datatypes.index[i]]
                print('Deleted: ',datatypes.index[i])
        else:
            num_cols.append(datatypes.index[i])
num_cols

Deleted:  Artist Name
Deleted:  Track Name


['Popularity',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'duration_in min/ms',
 'time_signature']

In [427]:
cat_cols

[]

In [428]:
cat_data = []
num_data = []
if(len(cat_cols)>0):
    cat_data = dataset[cat_cols]
if(len(num_cols)>0):
    num_data = dataset[num_cols]
y_data = dataset[target_column]

In [429]:
num_data,cat_data

(       Popularity  danceability  energy   key  loudness  mode  speechiness  \
 0            60.0         0.854   0.564   1.0    -4.964     1       0.0485   
 1            54.0         0.382   0.814   3.0    -7.230     1       0.0406   
 2            35.0         0.434   0.614   6.0    -8.334     1       0.0525   
 3            66.0         0.853   0.597  10.0    -6.528     0       0.0555   
 4            53.0         0.167   0.975   2.0    -4.279     1       0.2160   
 ...           ...           ...     ...   ...       ...   ...          ...   
 17991        35.0         0.166   0.109   7.0   -17.100     0       0.0413   
 17992        27.0         0.638   0.223  11.0   -10.174     0       0.0329   
 17993        34.0         0.558   0.981   4.0    -4.683     0       0.0712   
 17994        29.0         0.215   0.805   6.0   -12.757     0       0.1340   
 17995        43.0         0.400   0.853   4.0    -5.320     0       0.0591   
 
        acousticness  instrumentalness  liveness  

### Outlier Detection 

In [430]:
def outlier_detect(df):
    if (len(num_data)>0):        
        for i in df.describe().columns:
            Q1=df.describe().at['25%',i]
            Q3=df.describe().at['75%',i]
            IQR=Q3 - Q1
            LB=Q1 - 1.5 * IQR
            UB=Q3 + 1.5 * IQR
            x=np.array(df[i])
            p=[]
            for j in x:
                if j < LB or j>UB:
                   p.append(j)
            print('\n Outliers for Column : ', i, ' Outliers count ', len(p))
            print(p)
    else:
        print("Num_data is empty")

        
outlier_detect(num_data)


 Outliers for Column :  Popularity  Outliers count  41
[99.0, 93.0, 98.0, 91.0, 95.0, 92.0, 95.0, 94.0, 96.0, 95.0, 95.0, 94.0, 95.0, 94.0, 94.0, 93.0, 97.0, 91.0, 93.0, 92.0, 91.0, 95.0, 94.0, 92.0, 100.0, 92.0, 95.0, 95.0, 97.0, 95.0, 93.0, 100.0, 97.0, 94.0, 95.0, 97.0, 92.0, 96.0, 91.0, 96.0, 92.0]

 Outliers for Column :  danceability  Outliers count  31
[0.0809, 0.0646, 0.0814, 0.0789, 0.0896, 0.0726, 0.0599, 0.0855, 0.0862, 0.0876, 0.0882, 0.0755, 0.0731, 0.0828, 0.0892, 0.0887, 0.0764, 0.0596, 0.0847, 0.0906, 0.0756, 0.0644, 0.0653, 0.075, 0.08900000000000001, 0.069, 0.065, 0.0862, 0.0697, 0.0808, 0.085]

 Outliers for Column :  energy  Outliers count  0
[]

 Outliers for Column :  key  Outliers count  0
[]

 Outliers for Column :  loudness  Outliers count  818
[-20.316, -19.203, -19.539, -16.642, -18.250999999999998, -20.924, -16.835, -21.749000000000002, -18.827, -19.131, -18.992, -17.527, -17.293, -18.072, -17.19, -21.35, -18.566, -16.082, -22.639, -16.225, -24.735, -17.666


 Outliers for Column :  mode  Outliers count  0
[]

 Outliers for Column :  speechiness  Outliers count  2034
[0.21600000000000003, 0.292, 0.302, 0.418, 0.17600000000000002, 0.409, 0.221, 0.23399999999999999, 0.24600000000000002, 0.156, 0.222, 0.311, 0.44299999999999995, 0.54, 0.258, 0.306, 0.191, 0.282, 0.16699999999999998, 0.35100000000000003, 0.359, 0.226, 0.217, 0.287, 0.215, 0.207, 0.188, 0.21100000000000002, 0.21899999999999997, 0.37, 0.168, 0.29, 0.266, 0.39799999999999996, 0.231, 0.336, 0.342, 0.212, 0.161, 0.251, 0.382, 0.5, 0.163, 0.5, 0.17, 0.259, 0.20199999999999999, 0.18600000000000003, 0.157, 0.376, 0.18100000000000002, 0.253, 0.321, 0.166, 0.32799999999999996, 0.35100000000000003, 0.214, 0.335, 0.321, 0.17, 0.172, 0.204, 0.205, 0.212, 0.447, 0.184, 0.298, 0.249, 0.268, 0.306, 0.258, 0.29, 0.2, 0.325, 0.32799999999999996, 0.16699999999999998, 0.35100000000000003, 0.268, 0.188, 0.307, 0.39, 0.223, 0.41600000000000004, 0.17800000000000002, 0.20199999999999999, 0.292, 0.333


 Outliers for Column :  instrumentalness  Outliers count  2408
[0.929, 0.636, 0.855, 0.93, 0.856, 0.892, 0.693, 0.9259999999999999, 0.885, 0.807, 0.972, 0.897, 0.5429999999999999, 0.794, 0.624, 0.6970000000000001, 0.892, 0.835, 0.703, 0.513, 0.899, 0.578, 0.853, 0.6890000000000001, 0.9129999999999999, 0.726, 0.502, 0.7909999999999999, 0.9059999999999999, 0.9590000000000001, 0.642, 0.8059999999999999, 0.919, 0.878, 0.6709999999999999, 0.57, 0.914, 0.8290000000000001, 0.7829999999999999, 0.705, 0.873, 0.96, 0.532, 0.752, 0.865, 0.821, 0.937, 0.8640000000000001, 0.78, 0.8290000000000001, 0.951, 0.657, 0.85, 0.81, 0.813, 0.561, 0.873, 0.835, 0.603, 0.562, 0.7509999999999999, 0.635, 0.8909999999999999, 0.899, 0.875, 0.648, 0.7859999999999999, 0.857, 0.8759999999999999, 0.9059999999999999, 0.932, 0.711, 0.853, 0.5820000000000001, 0.852, 0.69, 0.815, 0.843, 0.7090000000000001, 0.531, 0.75, 0.578, 0.9470000000000001, 0.9520000000000001, 0.7070000000000001, 0.85, 0.667, 0.687, 0.816, 0.662, 0.


 Outliers for Column :  tempo  Outliers count  36
[207.92, 205.773, 205.835, 209.06, 207.476, 207.452, 210.16400000000002, 205.528, 209.38299999999998, 214.396, 34.132, 216.09099999999998, 207.72, 212.049, 207.373, 207.90599999999998, 205.59799999999998, 217.416, 209.84, 207.72, 30.557, 208.63400000000001, 208.58900000000003, 207.80599999999998, 208.16, 209.905, 216.02, 205.97299999999998, 207.46900000000002, 216.053, 207.93400000000003, 208.067, 207.72, 205.57, 216.053, 217.416]

 Outliers for Column :  duration_in min/ms  Outliers count  3245
[3.105783333, 4.33045, 4.44025, 4.015633333, 3.5037833330000003, 2.8176333330000003, 3.014916667, 3.3851166669999997, 403027.0, 3.5788833330000003, 4.747333333, 3.81156667, 4.98235, 2.7204, 3.5860000000000003, 2.48178333, 811077.0, 3.545833333, 2.80733333, 3.34355, 6.05555, 387547.0, 5.735216667, 3.181333333, 2.84688333, 6.90355, 4.7578833330000005, 652320.0, 5.09355, 2.408883333, 3.07021667, 2.96911667, 4.77033333, 2.5801, 385920.0, 2.71621666

### Treat Missing Values

In [431]:
if len(num_data):
    from sklearn.impute import SimpleImputer
    imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
    imputer.fit(num_data.iloc[:,:].values)
    num_data = pd.DataFrame(imputer.transform(num_data.iloc[:,:].values))
    num_data.columns = num_cols
num_data

Popularity  danceability  energy   key  loudness  mode  speechiness  \
0            60.0         0.854   0.564   1.0    -4.964   1.0       0.0485   
1            54.0         0.382   0.814   3.0    -7.230   1.0       0.0406   
2            35.0         0.434   0.614   6.0    -8.334   1.0       0.0525   
3            66.0         0.853   0.597  10.0    -6.528   0.0       0.0555   
4            53.0         0.167   0.975   2.0    -4.279   1.0       0.2160   
...           ...           ...     ...   ...       ...   ...          ...   
17991        35.0         0.166   0.109   7.0   -17.100   0.0       0.0413   
17992        27.0         0.638   0.223  11.0   -10.174   0.0       0.0329   
17993        34.0         0.558   0.981   4.0    -4.683   0.0       0.0712   
17994        29.0         0.215   0.805   6.0   -12.757   0.0       0.1340   
17995        43.0         0.400   0.853   4.0    -5.320   0.0       0.0591   

       acousticness  instrumentalness  liveness  valence    tempo  \
0          0.017100          0.177562    0.0849   0.8990  134.071   
1          0.001100          0.004010    0.1010   0.5690  116.454   
2          0.486000          0.000196    0.3940   0.7870  147.681   
3          0.021200          0.177562    0.1220   0.5690  107.033   
4          0.000169          0.016100    0.1720   0.0918  199.060   
...             ...               ...       ...      ...      ...   
17991      0.993000          0.824000    0.0984   0.1770  171.587   
17992      0.858000          0.000016    0.0705   0.3350   73.016   
17993      0.000030          0.000136    0.6660   0.2620  105.000   
17994      0.001290          0.916000    0.2560   0.3550  131.363   
17995      0.006040          0.212000    0.3340   0.3770  138.102   

       duration_in min/ms  time_signature  
0                234596.0             4.0  
1                251733.0             4.0  
2                109667.0             4.0  
3                173968.0             4.0  
4                229960.0             4.0  
...                   ...             ...  
17991            193450.0             3.0  
17992            257067.0             4.0  
17993            216222.0             4.0  
17994            219693.0             4.0  
17995            182227.0             4.0  

[17996 rows x 14 columns]

In [432]:
if(len(cat_data)>0 and len(num_data)>0):
    print("1")
    df = pd.concat([num_data,cat_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
    df.isnull().sum()
elif(len(num_data) > 0):
    print("2")
    df = pd.concat([num_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
else:
    print("3")
    df = pd.concat([cat_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
(df)

2


Popularity  danceability  energy   key  loudness  mode  speechiness  \
0            60.0         0.854   0.564   1.0    -4.964   1.0       0.0485   
1            54.0         0.382   0.814   3.0    -7.230   1.0       0.0406   
2            35.0         0.434   0.614   6.0    -8.334   1.0       0.0525   
3            66.0         0.853   0.597  10.0    -6.528   0.0       0.0555   
4            53.0         0.167   0.975   2.0    -4.279   1.0       0.2160   
...           ...           ...     ...   ...       ...   ...          ...   
17991        35.0         0.166   0.109   7.0   -17.100   0.0       0.0413   
17992        27.0         0.638   0.223  11.0   -10.174   0.0       0.0329   
17993        34.0         0.558   0.981   4.0    -4.683   0.0       0.0712   
17994        29.0         0.215   0.805   6.0   -12.757   0.0       0.1340   
17995        43.0         0.400   0.853   4.0    -5.320   0.0       0.0591   

       acousticness  instrumentalness  liveness  valence    tempo  \
0          0.017100          0.177562    0.0849   0.8990  134.071   
1          0.001100          0.004010    0.1010   0.5690  116.454   
2          0.486000          0.000196    0.3940   0.7870  147.681   
3          0.021200          0.177562    0.1220   0.5690  107.033   
4          0.000169          0.016100    0.1720   0.0918  199.060   
...             ...               ...       ...      ...      ...   
17991      0.993000          0.824000    0.0984   0.1770  171.587   
17992      0.858000          0.000016    0.0705   0.3350   73.016   
17993      0.000030          0.000136    0.6660   0.2620  105.000   
17994      0.001290          0.916000    0.2560   0.3550  131.363   
17995      0.006040          0.212000    0.3340   0.3770  138.102   

       duration_in min/ms  time_signature  Class  
0                234596.0             4.0      5  
1                251733.0             4.0     10  
2                109667.0             4.0      6  
3                173968.0             4.0      5  
4                229960.0             4.0     10  
...                   ...             ...    ...  
17991            193450.0             3.0      6  
17992            257067.0             4.0      2  
17993            216222.0             4.0      8  
17994            219693.0             4.0      8  
17995            182227.0             4.0     10  

[17996 rows x 15 columns]

In [433]:
cat_data = df[cat_cols]
num_data = df[num_cols]
y_data = df[target_column]
df.drop(target_column,inplace=True,axis=1)
len(y_data)

17996

### One-hot encoding the categorical data

In [434]:
#if len(cat_cols):
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
X_encoded = pd.DataFrame(OH_encoder.fit_transform(df[cat_cols]))

# One-hot encoding removed index; put it back
X_encoded.index = df.index

# Remove categorical columns (will replace with one-hot encoding)
num_X = df.drop(cat_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X = pd.concat([num_X, X_encoded], axis=1)

In [435]:
OH_X

Popularity  danceability  energy   key  loudness  mode  speechiness  \
0            60.0         0.854   0.564   1.0    -4.964   1.0       0.0485   
1            54.0         0.382   0.814   3.0    -7.230   1.0       0.0406   
2            35.0         0.434   0.614   6.0    -8.334   1.0       0.0525   
3            66.0         0.853   0.597  10.0    -6.528   0.0       0.0555   
4            53.0         0.167   0.975   2.0    -4.279   1.0       0.2160   
...           ...           ...     ...   ...       ...   ...          ...   
17991        35.0         0.166   0.109   7.0   -17.100   0.0       0.0413   
17992        27.0         0.638   0.223  11.0   -10.174   0.0       0.0329   
17993        34.0         0.558   0.981   4.0    -4.683   0.0       0.0712   
17994        29.0         0.215   0.805   6.0   -12.757   0.0       0.1340   
17995        43.0         0.400   0.853   4.0    -5.320   0.0       0.0591   

       acousticness  instrumentalness  liveness  valence    tempo  \
0          0.017100          0.177562    0.0849   0.8990  134.071   
1          0.001100          0.004010    0.1010   0.5690  116.454   
2          0.486000          0.000196    0.3940   0.7870  147.681   
3          0.021200          0.177562    0.1220   0.5690  107.033   
4          0.000169          0.016100    0.1720   0.0918  199.060   
...             ...               ...       ...      ...      ...   
17991      0.993000          0.824000    0.0984   0.1770  171.587   
17992      0.858000          0.000016    0.0705   0.3350   73.016   
17993      0.000030          0.000136    0.6660   0.2620  105.000   
17994      0.001290          0.916000    0.2560   0.3550  131.363   
17995      0.006040          0.212000    0.3340   0.3770  138.102   

       duration_in min/ms  time_signature  
0                234596.0             4.0  
1                251733.0             4.0  
2                109667.0             4.0  
3                173968.0             4.0  
4                229960.0             4.0  
...                   ...             ...  
17991            193450.0             3.0  
17992            257067.0             4.0  
17993            216222.0             4.0  
17994            219693.0             4.0  
17995            182227.0             4.0  

[17996 rows x 14 columns]

### Sampling/ Unbalanced Check

In [436]:
count = y_data.value_counts()
print(count)
print(max(count))
print(min(count))
cond = min(count)/max(count)
print(cond)

10    4949
6     2587
9     2524
8     1854
5     1447
1     1373
2     1272
0      625
7      576
3      402
4      387
Name: Class, dtype: int64
4949
387
0.07819761567993534


### Label encoding y_data

In [437]:
from sklearn.preprocessing import LabelEncoder
if(y_data.dtypes == "object"):
    print(y_data.dtypes)
    le = LabelEncoder()
    y_data = le.fit_transform(y_data)
    y_data

In [438]:
from imblearn.over_sampling import ADASYN
from collections import Counter
if(cond<0.3):
    counter = Counter(y_data)
    print('before :',counter)
    ADA = ADASYN(random_state=130,sampling_strategy='minority')
    OH_X,y_data = ADA.fit_resample(OH_X,y_data)
    counter = Counter(y_data)
    print("after :",counter)

before : Counter({10: 4949, 6: 2587, 9: 2524, 8: 1854, 5: 1447, 1: 1373, 2: 1272, 0: 625, 7: 576, 3: 402, 4: 387})
after : Counter({10: 4949, 4: 4933, 6: 2587, 9: 2524, 8: 1854, 5: 1447, 1: 1373, 2: 1272, 0: 625, 7: 576, 3: 402})


### Scaling

In [439]:
from sklearn.preprocessing import StandardScaler

In [440]:
sc_x = StandardScaler()

In [441]:
OH_X = sc_x.fit_transform(OH_X)

In [442]:
OH_X

array([[ 0.80315431,  1.92127861, -0.35716539, ...,  0.40388938,
         0.57870263,  0.22584799],
       [ 0.44817544, -1.11246431,  0.74128451, ..., -0.19020125,
         0.71211596,  0.22584799],
       [-0.67592434, -0.7782384 , -0.13747541, ...,  0.86285364,
        -0.39388269,  0.22584799],
       ...,
       [ 1.21459198,  0.0118576 ,  0.34235093, ...,  1.21493516,
        -1.24762017,  0.22584799],
       [ 1.09897005, -0.2632764 ,  1.06294303, ...,  1.34976399,
        -1.24762284,  0.22584799],
       [ 1.09897005, -0.27360098,  1.09867368, ...,  1.34754642,
        -1.24762254,  0.22584799]])

In [443]:
model_accuracies = {}

In [444]:
from sklearn.metrics import roc_auc_score,accuracy_score, classification_report
def write_report(model, remarks, model_name):
 preds = model.predict(X_test)
 report = classification_report(y_test,preds)
 balanced_accuracy = '-'
 roc_score = roc_auc_score(y_test, preds)
 accuracyscore = accuracy_score(y_test, preds)
 print(f'\n{model}\n {report}\n  accuracy score: {accuracyscore}\n Roc auc score: {roc_score}\n Remarks: {remarks}')
 with open(".//reports//"+model_name+"_report.txt", "w") as myfile:
   myfile.write(f'\n{model}\n {report}\n accuracy score: {accuracyscore}\n Roc auc score: {roc_score}\n Remarks: {remarks}')

### Splitting Dataset

In [445]:
from sklearn.model_selection import train_test_split

In [446]:
X_train,X_test,y_train,y_test = train_test_split(OH_X,y_data,test_size=0.2,random_state=0)

## MODEL TRAINING

### Logistic Regression

In [447]:
from sklearn.linear_model import LogisticRegression
LR_classifier = LogisticRegression(random_state = 0)
LR_classifier.fit(X_train, y_train)

y_pred_lr = LR_classifier.predict(X_test)

C:\Anaconda3\envs\tensorflow_en\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [448]:
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)
lr_accuracy = accuracy_score(y_test, y_pred_lr)
model_accuracies["LogisticRegression"] = lr_accuracy
print(lr_accuracy)

[[ 59   0   0   7  59   0   0   8   0   0   0]
 [  0   0   8   0   0  13  42   0  20  23 182]
 [  1   0  96   0   0   3  16   0   7  30 105]
 [  6   0   0  43  14   0   0   3   0   1   0]
 [  6   0   0   5 962   0   0   0   0   5   0]
 [  0   0   9   0   0 189  12   0   3  46  38]
 [  0   0  31   0   0  23 110   2  28  62 267]
 [  4   0   0   1   4   0   0 100   0   0   0]
 [  0   0   1   0   0   2   8   0 176   0 162]
 [  7   0  28   4  58  37  27   0   1 219 162]
 [  2   0  42   0  28  11  53   0  80  76 672]]
0.5823907740075405


In [449]:
# write_report(LR_classifier,"good Model","Logistic Regression")

### Decision Tree Classifier

In [450]:
from sklearn.tree import DecisionTreeClassifier
DT_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
DT_classifier.fit(X_train, y_train)

y_pred_dr = DT_classifier.predict(X_test)

In [451]:
cm = confusion_matrix(y_test, y_pred_dr)
print(cm)
dt_accuracy = accuracy_score(y_test, y_pred_dr)
model_accuracies["DecisionTreeClassifer"] = dt_accuracy
print(dt_accuracy)

[[ 76   0   0  16  25   0   0   7   0   7   2]
 [  0  24  12   0   0  11 128   0  12  25  76]
 [  0  26  75   0   0   5  39   0  10  21  82]
 [  9   0   0  43   4   0   0   5   0   5   1]
 [ 15   0   0   5 949   0   0   0   0   5   4]
 [  0  13   9   0   0 161  20   0   1  71  22]
 [  0 132  40   0   0  17 111   0  35  53 135]
 [  6   0   0   5   0   0   0  97   0   1   0]
 [  0  13   7   0   0   1  25   0 167   7 129]
 [ 11  38  32   5  14  51  67   0   9 211 105]
 [  7 133  78   3  10  29 151   0 140 114 299]]
0.49079618540696385


In [452]:
# write_report(DT_classifier,"good Model","Decision Tree Classifer")

### Random Forest classifier

In [453]:
from sklearn.ensemble import RandomForestClassifier
nodes = [10,15,20,25,50,100,200]
accuracy =[]
for node in nodes:    
    RandomForestclassifier = RandomForestClassifier(criterion = 'entropy', random_state=0, n_estimators=node)
    RandomForestclassifier.fit(X_train,y_train)
    preds = RandomForestclassifier.predict(X_test)
    accs = accuracy_score(y_test,preds)
    accuracy.append(accs)
    print(confusion_matrix(y_test,preds),'No of Estimators: ', node,accs)

# sns.lineplot(x=nodes,y=accuracy)
model_accuracies["RandomForestclassifier"] = accs

[[ 82   0   0  11  34   0   0   4   0   1   1]
 [  0  23   9   0   0   7 114   0   7  13 115]
 [  0  15 102   0   0   9  35   0   5  18  74]
 [ 12   0   0  46   4   0   0   2   0   1   2]
 [  1   0   0   1 975   0   0   0   0   1   0]
 [  0   1  13   0   0 201  18   0   1  39  24]
 [  0  91  28   0   0  22 123   0  18  46 195]
 [  7   0   0   1   1   0   0 100   0   0   0]
 [  0   2   3   0   0   1  15   0 179   3 146]
 [ 11  14  24   4  16  57  62   0   5 247 103]
 [  5  71  51   3  17  28 119   0 114  78 478]] No of Estimators:  10 0.5668662674650699
[[ 84   0   0  11  32   0   0   3   0   2   1]
 [  0  13   9   0   0   7 118   0   8  13 120]
 [  0   8  97   0   0   9  34   0   6  19  85]
 [ 11   0   0  46   5   0   0   2   0   1   2]
 [  1   0   0   0 975   0   0   0   0   2   0]
 [  0   0   8   0   0 208  17   0   1  40  23]
 [  0  89  27   0   0  27 109   0  13  49 209]
 [  5   0   0   1   0   0   0 103   0   0   0]
 [  0   1   3   0   0   0  12   0 172   1 160]
 [ 10  11  20   4 

In [454]:
# write_report(RandomForestclassifier,"good Model","RandomForestClassifier")

### XgBoost Classifier

In [455]:
from xgboost import XGBClassifier   #XGBoostClassifier
XGboostclassifier = XGBClassifier(max_depth=6)
XGboostclassifier.fit(X_train, y_train)
y_pred = XGboostclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
xgboost_accuracy = accuracy_score(y_test, y_pred)
print(xgboost_accuracy)
model_accuracies['XGboostclassifier'] = xgboost_accuracy

[21:58:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Anaconda3\envs\tensorflow_en\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[[ 93   0   0   9  20   0   0   6   0   4   1]
 [  0   9   9   0   0   6  99   0   4  15 146]
 [  0   4 110   0   0   5  33   0   4  22  80]
 [  5   0   0  53   4   0   0   3   0   2   0]
 [  2   0   0   0 974   0   0   0   0   1   1]
 [  0   1   5   0   0 203  12   0   1  55  20]
 [  0  65  30   0   0  15 140   0  12  44 217]
 [  4   0   0   3   0   0   0 102   0   0   0]
 [  0   0   3   0   0   0  10   0 180   1 155]
 [ 10   7  15   0   6  49  55   0   0 283 118]
 [  3  31  42   5   8  21 111   0 101  80 562]]
0.6007984031936128


In [456]:
# write_report(XGboostclassifier,"good Model","XGboostclassifier")

### SVM Classifier


In [457]:
from sklearn.svm import SVC
SVCclassifier = SVC(kernel="rbf", random_state=0)
SVCclassifier.fit(X_train, y_train)
y_pred_svm = SVCclassifier.predict(X_test)

In [458]:
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)
svc_accuracy = accuracy_score(y_test, y_pred_svm)
print(svc_accuracy)
model_accuracies["SVCclassifier"] = svc_accuracy

[[ 75   0   1   6  42   0   0   4   0   3   2]
 [  0   5   5   0   0  12  47   0  14  30 175]
 [  0   0  96   0   0   4  14   1   3  24 116]
 [  6   0   0  43  11   0   0   3   0   2   2]
 [  1   0   0   0 977   0   0   0   0   0   0]
 [  0   0   9   0   0 206  10   0   0  44  28]
 [  0   7  22   0   0  30 104   1  17  48 294]
 [  6   0   0   1   1   0   0  99   0   1   1]
 [  0   0   1   0   0   0   5   0 148   1 194]
 [  6   0  21   1  31  47  24   0   0 267 146]
 [  4   0  27   0  25  10  42   0  58  80 718]]
0.6072299844754935


In [459]:
# write_report(SVCclassifier,"good Model","SVCclassifier")

### Naive Bayes 

In [460]:
from sklearn.naive_bayes import GaussianNB
GaussianNBclassifier = GaussianNB()
GaussianNBclassifier.fit(X_train, y_train)
y_pred_nb = GaussianNBclassifier.predict(X_test)

In [461]:
cm = confusion_matrix(y_test, y_pred_nb)
print(cm)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
print(nb_accuracy)
model_accuracies["GaussianNBclassifie"] = nb_accuracy

[[ 68   0   0   9  42   0   0  14   0   0   0]
 [  0   0  12   0   0  12  49   0  45  40 130]
 [  0   0  88   0   0   4  19   0  17  51  79]
 [ 19   0   0  33  12   0   0   3   0   0   0]
 [ 73   0   0  16 882   0   0   7   0   0   0]
 [  0   1   5   0   0 191  12   0   8  61  19]
 [  0   3  44   0   0  25 100   0  71  75 205]
 [  3   0   0   4   1   0   0 101   0   0   0]
 [  0   0   2   0   0   2  10   0 236   1  98]
 [ 22   0  38  21  37  38  26   1   8 221 131]
 [  5   2  54   3  23  14  69   0 182 113 499]]
0.536482590374806


In [462]:
# write_report(GaussianNBclassifier,"good Model","GaussianNBclassifier")

### Ada Boost

In [463]:
from sklearn.ensemble import AdaBoostClassifier
AdaboostClassifier = AdaBoostClassifier(n_estimators=100,learning_rate=1)
model = AdaboostClassifier.fit(X_train, y_train)
y_pred_ada = AdaboostClassifier.predict(X_test)

In [464]:
cm = confusion_matrix(y_test, y_pred_ada)
print(cm)
adaboost_accuracy = accuracy_score(y_test, y_pred_ada)
print(adaboost_accuracy)
model_accuracies["AdaboostClassifier"] = adaboost_accuracy

[[  0   0   0   2  20   0   0  98   0   3  10]
 [  0  37  34   0   0   3   2   0 208   2   2]
 [  0  29 106   0   0   4   1   0 116   1   1]
 [  1   0   0   8   7   0   0  42   0   2   7]
 [  3   0   0   5 504   0   0 466   0   0   0]
 [  0  45  22   0   0  39   1   0 168  17   5]
 [  0  68  79   0   0  12   9   0 345   3   7]
 [  0   0   0   0   0   0   0 103   0   0   6]
 [  0   6   4   0   0   1   1   0 335   0   2]
 [  0 104 112   1  60  24   2  21 203  10   6]
 [  0 114  86   0  19   6   6   5 707   3  18]]
0.25925925925925924


In [465]:
# write_report(AdaboostClassifier,"Good report","AdaboostClassifier")

### Finding the best model

In [466]:
bestmodel = max(model_accuracies, key = model_accuracies.get)
print(bestmodel)
print(model_accuracies[bestmodel])

SVCclassifier
0.6072299844754935


In [467]:
# rfc=RandomForestClassifier(random_state=42)

In [468]:
# param_grid = { 
#     'n_estimators': [200, 500],
#     'max_features': ['auto', 'sqrt', 'log2'],
#     'max_depth' : [4,5,6,7,8],
#     'criterion' :['gini', 'entropy']
# }

In [469]:
# from sklearn.model_selection import GridSearchCV
# CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
# CV_rfc.fit(X_train, y_train)
# CV_rfc.best_params_

In [470]:
# rfc=RandomForestClassifier(random_state=42,criterion= 'gini',max_depth=4,max_features= 'auto',n_estimators= 200)

In [471]:
# rfc.fit(X_train, y_train)
# preds = rfc.predict(X_test)
# accs = accuracy_score(y_test,preds)
# accuracy.append(accs)
# print(confusion_matrix(y_test,preds),'Accuracy: ',accs)