# Imports and Dataset

In [433]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [434]:
dataset = pd.read_csv('.//datasets//heart_failure_clinical_records_dataset.csv')
dataset

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [435]:
if "Unnamed: 0" in dataset.columns:
    dataset.drop("Unnamed: 0",axis=1,inplace=True)
dataset

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

## Preprocessing

### Remove Date Columns

In [436]:
if "date" in dataset.columns:
    dataset.drop("date",inplace=True,axis=1)
    print("date Deleted")
if "Date" in dataset.columns:
    dataset.drop("Date",inplace=True,axis=1)
    print("Date Deleted")

### Remove Dollar signs

In [437]:
dollar = '$'
prices_list = []
if(len(dataset) > 100):
    for column in dataset.columns:
        X = dataset[column][:50].values
        for val in X:
            if( "$" in str(val)):
                prices_list.append(column)
                break;
            break;
            
prices_list

[]

In [438]:
new_2darray = []
if(prices_list):
    cost_values = dataset[prices_list].values
    for array in cost_values:
        new_array = []
        for val in array:
            new_val = (re.sub("[^0-9]", "", val))
            if new_val:
                new_val = float(new_val)
            else:
                new_val = np.NaN
            new_array.append(new_val)
        new_2darray.append(new_array)
new_2darray

[]

In [439]:
if(prices_list):
    prices_data = pd.DataFrame(new_2darray,columns= prices_list)

In [440]:
if(prices_list):
    dataset.drop(prices_list,inplace=True,axis=1)

In [441]:
if(prices_list):
    dataset[prices_list] = prices_data

### Define Index / ID Columns and Target Columns

In [442]:
target_column = 'DEATH_EVENT'
id1 = "id"

### Categorize into numerical and categorical

In [443]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [444]:
datatypes = dataset.dtypes
datatypes

age                         float64
anaemia                       int64
creatinine_phosphokinase      int64
diabetes                      int64
ejection_fraction             int64
high_blood_pressure           int64
platelets                   float64
serum_creatinine            float64
serum_sodium                  int64
sex                           int64
smoking                       int64
time                          int64
DEATH_EVENT                   int64
dtype: object

In [445]:
cat_cols = []
num_cols = []

columns = dataset.columns
if id1 in dataset.columns:
    dataset.drop(id1,inplace=True,axis=1)

for i in range(len(datatypes)):
    if datatypes.index[i] != target_column:
        if datatypes[i]=='object':
            unqval = dataset[datatypes.index[i]].nunique()
            if (unqval < 30):
                cat_cols.append(datatypes.index[i])
            else:
                del dataset[datatypes.index[i]]
                print('Deleted: ',datatypes.index[i])
        else:
            num_cols.append(datatypes.index[i])
num_cols

['age',
 'anaemia',
 'creatinine_phosphokinase',
 'diabetes',
 'ejection_fraction',
 'high_blood_pressure',
 'platelets',
 'serum_creatinine',
 'serum_sodium',
 'sex',
 'smoking',
 'time']

In [446]:
cat_cols

[]

In [447]:
cat_data = []
num_data = []
if(len(cat_cols)>0):
    cat_data = dataset[cat_cols]
if(len(num_cols)>0):
    num_data = dataset[num_cols]
y_data = dataset[target_column]

In [448]:
num_data,cat_data

(      age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
 0    75.0        0                       582         0                 20   
 1    55.0        0                      7861         0                 38   
 2    65.0        0                       146         0                 20   
 3    50.0        1                       111         0                 20   
 4    65.0        1                       160         1                 20   
 ..    ...      ...                       ...       ...                ...   
 294  62.0        0                        61         1                 38   
 295  55.0        0                      1820         0                 38   
 296  45.0        0                      2060         1                 60   
 297  45.0        0                      2413         0                 38   
 298  50.0        0                       196         0                 45   
 
      high_blood_pressure  platelets  serum_creatinine  serum_

### Outlier Detection 

In [449]:
def outlier_detect(df):
    if (len(num_data)>0):        
        for i in df.describe().columns:
            Q1=df.describe().at['25%',i]
            Q3=df.describe().at['75%',i]
            IQR=Q3 - Q1
            LB=Q1 - 1.5 * IQR
            UB=Q3 + 1.5 * IQR
            x=np.array(df[i])
            p=[]
            for j in x:
                if j < LB or j>UB:
                   p.append(j)
            print('\n Outliers for Column : ', i, ' Outliers count ', len(p))
            print(p)
    else:
        print("Num_data is empty")

        
outlier_detect(num_data)


 Outliers for Column :  age  Outliers count  0
[]

 Outliers for Column :  anaemia  Outliers count  0
[]

 Outliers for Column :  creatinine_phosphokinase  Outliers count  29
[7861, 2656, 1380, 3964, 7702, 5882, 5209, 1876, 1808, 4540, 1548, 1610, 2261, 1846, 2334, 2442, 3966, 1419, 1896, 1767, 2281, 2794, 2017, 2522, 2695, 1688, 1820, 2060, 2413]

 Outliers for Column :  diabetes  Outliers count  0
[]

 Outliers for Column :  ejection_fraction  Outliers count  2
[80, 70]

 Outliers for Column :  high_blood_pressure  Outliers count  0
[]

 Outliers for Column :  platelets  Outliers count  21
[454000.0, 47000.0, 451000.0, 461000.0, 497000.0, 621000.0, 850000.0, 507000.0, 448000.0, 75000.0, 70000.0, 73000.0, 481000.0, 504000.0, 62000.0, 533000.0, 25100.0, 451000.0, 51000.0, 543000.0, 742000.0]

 Outliers for Column :  serum_creatinine  Outliers count  29
[2.7, 9.4, 4.0, 5.8, 3.0, 3.5, 2.3, 3.0, 4.4, 6.8, 2.2, 2.7, 2.3, 2.9, 2.5, 2.3, 3.2, 3.7, 3.4, 6.1, 2.5, 2.4, 2.5, 3.5, 9.0, 5.0, 2.4

### Treat Missing Values

In [450]:
if len(num_data):
    from sklearn.impute import SimpleImputer
    imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
    imputer.fit(num_data.iloc[:,:].values)
    num_data = pd.DataFrame(imputer.transform(num_data.iloc[:,:].values))
    num_data.columns = num_cols
num_data

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0      0.0                     582.0       0.0               20.0   
1    55.0      0.0                    7861.0       0.0               38.0   
2    65.0      0.0                     146.0       0.0               20.0   
3    50.0      1.0                     111.0       0.0               20.0   
4    65.0      1.0                     160.0       1.0               20.0   
..    ...      ...                       ...       ...                ...   
294  62.0      0.0                      61.0       1.0               38.0   
295  55.0      0.0                    1820.0       0.0               38.0   
296  45.0      0.0                    2060.0       1.0               60.0   
297  45.0      0.0                    2413.0       0.0               38.0   
298  50.0      0.0                     196.0       0.0               45.0   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1.0  265000.00               1.9         130.0  1.0   
1                    0.0  263358.03               1.1         136.0  1.0   
2                    0.0  162000.00               1.3         129.0  1.0   
3                    0.0  210000.00               1.9         137.0  1.0   
4                    0.0  327000.00               2.7         116.0  0.0   
..                   ...        ...               ...           ...  ...   
294                  1.0  155000.00               1.1         143.0  1.0   
295                  0.0  270000.00               1.2         139.0  0.0   
296                  0.0  742000.00               0.8         138.0  0.0   
297                  0.0  140000.00               1.4         140.0  1.0   
298                  0.0  395000.00               1.6         136.0  1.0   

     smoking   time  
0        0.0    4.0  
1        0.0    6.0  
2        1.0    7.0  
3        0.0    7.0  
4        0.0    8.0  
..       ...    ...  
294      1.0  270.0  
295      0.0  271.0  
296      0.0  278.0  
297      1.0  280.0  
298      1.0  285.0  

[299 rows x 12 columns]

In [451]:
if(len(cat_data)>0 and len(num_data)>0):
    print("1")
    df = pd.concat([num_data,cat_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
    df.isnull().sum()
elif(len(num_data) > 0):
    print("2")
    df = pd.concat([num_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
else:
    print("3")
    df = pd.concat([cat_data,y_data],axis=1)
    df = df.dropna().reset_index(drop=True)
(df)

2


age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0      0.0                     582.0       0.0               20.0   
1    55.0      0.0                    7861.0       0.0               38.0   
2    65.0      0.0                     146.0       0.0               20.0   
3    50.0      1.0                     111.0       0.0               20.0   
4    65.0      1.0                     160.0       1.0               20.0   
..    ...      ...                       ...       ...                ...   
294  62.0      0.0                      61.0       1.0               38.0   
295  55.0      0.0                    1820.0       0.0               38.0   
296  45.0      0.0                    2060.0       1.0               60.0   
297  45.0      0.0                    2413.0       0.0               38.0   
298  50.0      0.0                     196.0       0.0               45.0   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1.0  265000.00               1.9         130.0  1.0   
1                    0.0  263358.03               1.1         136.0  1.0   
2                    0.0  162000.00               1.3         129.0  1.0   
3                    0.0  210000.00               1.9         137.0  1.0   
4                    0.0  327000.00               2.7         116.0  0.0   
..                   ...        ...               ...           ...  ...   
294                  1.0  155000.00               1.1         143.0  1.0   
295                  0.0  270000.00               1.2         139.0  0.0   
296                  0.0  742000.00               0.8         138.0  0.0   
297                  0.0  140000.00               1.4         140.0  1.0   
298                  0.0  395000.00               1.6         136.0  1.0   

     smoking   time  DEATH_EVENT  
0        0.0    4.0            1  
1        0.0    6.0            1  
2        1.0    7.0            1  
3        0.0    7.0            1  
4        0.0    8.0            1  
..       ...    ...          ...  
294      1.0  270.0            0  
295      0.0  271.0            0  
296      0.0  278.0            0  
297      1.0  280.0            0  
298      1.0  285.0            0  

[299 rows x 13 columns]

In [452]:
cat_data = df[cat_cols]
num_data = df[num_cols]
y_data = df[target_column]
df.drop(target_column,inplace=True,axis=1)
len(y_data)

299

In [453]:
#if len(cat_cols):
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
X_encoded = pd.DataFrame(OH_encoder.fit_transform(df[cat_cols]))

# One-hot encoding removed index; put it back
X_encoded.index = df.index

# Remove categorical columns (will replace with one-hot encoding)
num_X = df.drop(cat_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X = pd.concat([num_X, X_encoded], axis=1)

In [454]:
OH_X

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0      0.0                     582.0       0.0               20.0   
1    55.0      0.0                    7861.0       0.0               38.0   
2    65.0      0.0                     146.0       0.0               20.0   
3    50.0      1.0                     111.0       0.0               20.0   
4    65.0      1.0                     160.0       1.0               20.0   
..    ...      ...                       ...       ...                ...   
294  62.0      0.0                      61.0       1.0               38.0   
295  55.0      0.0                    1820.0       0.0               38.0   
296  45.0      0.0                    2060.0       1.0               60.0   
297  45.0      0.0                    2413.0       0.0               38.0   
298  50.0      0.0                     196.0       0.0               45.0   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1.0  265000.00               1.9         130.0  1.0   
1                    0.0  263358.03               1.1         136.0  1.0   
2                    0.0  162000.00               1.3         129.0  1.0   
3                    0.0  210000.00               1.9         137.0  1.0   
4                    0.0  327000.00               2.7         116.0  0.0   
..                   ...        ...               ...           ...  ...   
294                  1.0  155000.00               1.1         143.0  1.0   
295                  0.0  270000.00               1.2         139.0  0.0   
296                  0.0  742000.00               0.8         138.0  0.0   
297                  0.0  140000.00               1.4         140.0  1.0   
298                  0.0  395000.00               1.6         136.0  1.0   

     smoking   time  
0        0.0    4.0  
1        0.0    6.0  
2        1.0    7.0  
3        0.0    7.0  
4        0.0    8.0  
..       ...    ...  
294      1.0  270.0  
295      0.0  271.0  
296      0.0  278.0  
297      1.0  280.0  
298      1.0  285.0  

[299 rows x 12 columns]

### Sampling/ Unbalanced Check

In [455]:
count = y_data.value_counts()
print(count)
print(max(count))
print(min(count))
cond = min(count)/max(count)
print(cond)

0    203
1     96
Name: DEATH_EVENT, dtype: int64
203
96
0.4729064039408867


In [456]:
from imblearn.over_sampling import ADASYN
from collections import Counter
if(cond<0.3):
    counter = Counter(y_data)
    print('before :',counter)
    ADA = ADASYN(random_state=130,sampling_strategy='minority')
    OH_X,y_data = ADA.fit_resample(OH_X,y_data)
    counter = Counter(y_data)
    print("after :",counter)

### Scaling

In [457]:
from sklearn.preprocessing import StandardScaler

In [458]:
sc_x = StandardScaler()

In [459]:
OH_X = sc_x.fit_transform(OH_X)

In [460]:
OH_X

array([[ 1.19294523e+00, -8.71104775e-01,  1.65728387e-04, ...,
         7.35688190e-01, -6.87681906e-01, -1.62950241e+00],
       [-4.91279276e-01, -8.71104775e-01,  7.51463953e+00, ...,
         7.35688190e-01, -6.87681906e-01, -1.60369074e+00],
       [ 3.50832977e-01, -8.71104775e-01, -4.49938761e-01, ...,
         7.35688190e-01,  1.45416070e+00, -1.59078490e+00],
       ...,
       [-1.33339153e+00, -8.71104775e-01,  1.52597865e+00, ...,
        -1.35927151e+00, -6.87681906e-01,  1.90669738e+00],
       [-1.33339153e+00, -8.71104775e-01,  1.89039811e+00, ...,
         7.35688190e-01,  1.45416070e+00,  1.93250906e+00],
       [-9.12335403e-01, -8.71104775e-01, -3.98321274e-01, ...,
         7.35688190e-01,  1.45416070e+00,  1.99703825e+00]])

In [461]:
model_accuracies = {}

In [462]:
from sklearn.metrics import roc_auc_score,accuracy_score, classification_report
def write_report(model, remarks, model_name):
 preds = model.predict(X_test)
 report = classification_report(y_test,preds)
 balanced_accuracy = '-'
 roc_score = roc_auc_score(y_test, preds)
 accuracyscore = accuracy_score(y_test, preds)
 print(f'\n{model}\n {report}\n  accuracy score: {accuracyscore}\n Roc auc score: {roc_score}\n Remarks: {remarks}')
 with open(".//reports//"+model_name+"_report.txt", "w") as myfile:
   myfile.write(f'\n{model}\n {report}\n accuracy score: {accuracyscore}\n Roc auc score: {roc_score}\n Remarks: {remarks}')

### Splitting Dataset

In [463]:
from sklearn.model_selection import train_test_split

In [464]:
X_train,X_test,y_train,y_test = train_test_split(OH_X,y_data,test_size=0.2,random_state=0)

## MODEL TRAINING

### Random Forest classifier

In [465]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
nodes = [10,15,20,25,50,100,200]
accuracy =[]
for node in nodes:    
    RandomForestclassifier = RandomForestClassifier(criterion = 'entropy', random_state=0, n_estimators=node)
    RandomForestclassifier.fit(X_train,y_train)
    preds = RandomForestclassifier.predict(X_test)
    accs = accuracy_score(y_test,preds)
    accuracy.append(accs)
    print(confusion_matrix(y_test,preds),'No of Estimators: ', node,accs)

# sns.lineplot(x=nodes,y=accuracy)
model_accuracies["RandomForestclassifier"] = accs

[[36  1]
 [10 13]] No of Estimators:  10 0.8166666666666667
[[35  2]
 [ 9 14]] No of Estimators:  15 0.8166666666666667
[[36  1]
 [13 10]] No of Estimators:  20 0.7666666666666667
[[34  3]
 [10 13]] No of Estimators:  25 0.7833333333333333
[[36  1]
 [10 13]] No of Estimators:  50 0.8166666666666667
[[36  1]
 [ 8 15]] No of Estimators:  100 0.85
[[36  1]
 [ 8 15]] No of Estimators:  200 0.85


In [466]:
write_report(RandomForest_classifier,"good Model","RandomForestClassifier")


RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)
               precision    recall  f1-score   support

           0       0.82      0.97      0.89        37
           1       0.94      0.65      0.77        23

    accuracy                           0.85        60
   macro avg       0.88      0.81      0.83        60
weighted avg       0.86      0.85      0.84        60

  accuracy score: 0.85
 Roc auc score: 0.8125734430082258
 Remarks: good Model


### XgBoost Classifier

In [467]:
from xgboost import XGBClassifier   #XGBoostClassifier
XGboostclassifier = XGBClassifier(max_depth=6)
XGboostclassifier.fit(X_train, y_train)
y_pred = XGboostclassifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
xgboost_accuracy = accuracy_score(y_test, y_pred)
model_accuracies['XGboostclassifier'] = xgboost_accuracy

[16:18:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[33  4]
 [ 7 16]]


C:\Anaconda3\envs\tensorflow_en\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


In [468]:
write_report(XGboostclassifier,"good Model","XGboostclassifier")


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)
               precision    recall  f1-score   support

           0       0.82      0.89      0.86        37
           1       0.80      0.70      0.74        23

    accuracy                           0.82        60
   macro avg       0.81      0.79      0.80        60
weighted avg       0.82      0.82      0.81        60

  accuracy score: 0.8166666666666667
 Roc auc score: 0.7937720329024677
 Remarks: good Mo

### SVM Classifier


In [469]:
from sklearn.svm import SVC

In [470]:
SVCclassifier = SVC(kernel="rbf", random_state=0)
SVCclassifier.fit(X_train, y_train)
y_pred = SVCclassifier.predict(X_test)

In [471]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svc_accuracy = accuracy_score(y_test, y_pred)
model_accuracies["SVCclassifier"] = svc_accuracy

[[36  1]
 [10 13]]


In [472]:
write_report(SVCclassifier,"good Model","SVCclassifier")


SVC(random_state=0)
               precision    recall  f1-score   support

           0       0.78      0.97      0.87        37
           1       0.93      0.57      0.70        23

    accuracy                           0.82        60
   macro avg       0.86      0.77      0.79        60
weighted avg       0.84      0.82      0.80        60

  accuracy score: 0.8166666666666667
 Roc auc score: 0.7690951821386603
 Remarks: good Model


### Naive Bayes 

In [473]:
from sklearn.naive_bayes import GaussianNB

In [474]:
GaussianNBclassifier = GaussianNB()
GaussianNBclassifier.fit(X_train, y_train)
y_pred = GaussianNBclassifier.predict(X_test)

In [475]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naivebayes_accuracy = accuracy_score(y_test, y_pred)
model_accuracies["GaussianNBclassifie"] = naivebayes_accuracy

[[34  3]
 [16  7]]


In [476]:
write_report(GaussianNBclassifier,"good Model","GaussianNBclassifier")


GaussianNB()
               precision    recall  f1-score   support

           0       0.68      0.92      0.78        37
           1       0.70      0.30      0.42        23

    accuracy                           0.68        60
   macro avg       0.69      0.61      0.60        60
weighted avg       0.69      0.68      0.64        60

  accuracy score: 0.6833333333333333
 Roc auc score: 0.6116333725029377
 Remarks: good Model


### Ada Boost

In [477]:
from sklearn.ensemble import AdaBoostClassifier

In [478]:
AdaboostClassifier = AdaBoostClassifier(n_estimators=100,learning_rate=1)
model = AdaboostClassifier.fit(X_train, y_train)
y_pred = AdaboostClassifier.predict(X_test)

In [479]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
adaboost_accuracy = accuracy_score(y_test, y_pred)
model_accuracies["AdaboostClassifier"] = adaboost_accuracy

[[33  4]
 [10 13]]


In [480]:
write_report(AdaboostClassifier,"Good report","AdaboostClassifier")


AdaBoostClassifier(learning_rate=1, n_estimators=100)
               precision    recall  f1-score   support

           0       0.77      0.89      0.82        37
           1       0.76      0.57      0.65        23

    accuracy                           0.77        60
   macro avg       0.77      0.73      0.74        60
weighted avg       0.77      0.77      0.76        60

  accuracy score: 0.7666666666666667
 Roc auc score: 0.7285546415981198
 Remarks: Good report


### Finding the best model

In [481]:
bestmodel = max(model_accuracies, key = model_accuracies.get)
print(bestmodel)
print(model_accuracies[bestmodel])

RandomForest
0.85


In [482]:
# rfc=RandomForestClassifier(random_state=42)

In [483]:
# param_grid = { 
#     'n_estimators': [200, 500],
#     'max_features': ['auto', 'sqrt', 'log2'],
#     'max_depth' : [4,5,6,7,8],
#     'criterion' :['gini', 'entropy']
# }

In [484]:
# from sklearn.model_selection import GridSearchCV
# CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
# CV_rfc.fit(X_train, y_train)
# CV_rfc.best_params_

In [485]:
# rfc=RandomForestClassifier(random_state=42,criterion= 'gini',max_depth=4,max_features= 'auto',n_estimators= 200)

In [486]:
# rfc.fit(X_train, y_train)
# preds = rfc.predict(X_test)
# accs = accuracy_score(y_test,preds)
# accuracy.append(accs)
# print(confusion_matrix(y_test,preds),'Accuracy: ',accs)